### PR TITLE
Add HTML5 boolean attributes to the list

### PR DESCRIPTION
**Pull request by cillianderoiste**
I noticed that when rendering a video element, `tal:attributes="autoplay python:''"` was rendering as autoplay='' which is treated as a positive value in the browser, enabling autoplay. By extending the list of boolean HTML attributes, the attribute is now dropped when empty.
I've included all the boolean attributes, and kept the old attributes, to maintain backwards compatibility. 

Here's a list of all HTML5 boolean attributes, derived from https://html.spec.whatwg.org/multipage/indices.html#attributes-3
allowfullscreen 
async 
autofocus 
autoplay 
checked 
controls 
default 
defer 
disabled 
formnovalidate 
inert 
ismap 
itemscope 
loop 
multiple 
muted 
nomodule 
novalidate 
open 
playsinline 
readonly 
required 
reversed 
selected 
shadowrootclonable 
shadowrootdelegatesfocus 
shadowrootserializable

### CODE REVIEW

**Review by icemac — APPROVED** [review]

**Comment by icemac** [comment]
Thank you for this PR. The broken tests seem to be unrelated to your changes, I will take care of them.

**Comment by tseaver** [comment]
The breakage induced in `zope.proxy` by the `zope.interface v7.0` release should be [fixed shortly](https://github.com/zopefoundation/zope.interface/pull/313).

**Comment by tseaver** [comment]
I have restarted the failed jobs, which should be fixed by the [release of `zope.interfface 7.0.1`](https://pypi.org/project/zope.interface/7.0.1/)

**Comment by icemac** [comment]
@tseaver Thank you for fixing this so quickly.

**Comment by icemac** [comment]
@cillianderoiste Released as https://pypi.org/project/z3c.pt/4.4/

**Comment by cillianderoiste** [comment]
Fantastic, thanks so much!

**Pull request merged**
