### PR TITLE
Prevent interpolations in comments

### PR DESCRIPTION
**Pull request by d-maurer**
Fixes https://github.com/zopefoundation/Zope/issues/716

### CODE REVIEW

**Comment by d-maurer** [comment]
The Pyhton 3.4 test fails due to a problem unrelated to this change.

**Comment by dataflake** [comment]
@icemac Michael can you either create a new release or give me maintainer access on PyPI? I want the release so I can pin the new version for the Zope 4 release.

**Comment by icemac** [comment]
@dataflake I added you as owner of this package on PyPI.

**Comment by dataflake** [comment]
Thank you!

**Pull request merged**
