### PR TITLE
Python 3.x support

### PR DESCRIPTION
**Pull request by icemac**
+ dropped Python 2.6 support.

### CODE REVIEW

**Comment by jamadden** [comment]
Pretty much ditto https://github.com/zopefoundation/z3c.ptcompat/pull/1#issuecomment-244048085 (except this is an active repository).

**Comment by mgedmin** [comment]
LGTM, with the same proviso that I'd prefer the https://github.com/zopefoundation/zope.viewlet/blob/master/.travis.yml approach.

**Comment by icemac** [comment]
Okay, if zope.viewlet does it the canonical way, I'll use it here, too. (Plus trying PyPy3 which I do not have installed on my computer.)

**Comment by icemac** [comment]
@hannosch I'd like to release these changes as 3.0 but I do not have the rights on PyPI. Please add me (`icemac`) to the list of packages maintainers there.

**Comment by hannosch** [comment]
@icemac gave you owner rights on PyPi.

**Pull request merged**
